### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by pviotti** [ssidhanta/ConSpecTool#1]
Hi,

I can't run the tool. On Linux I get the following error when calling `./callConspecChecker.sh RYW`:

```
./callConspecChecker.sh: line 3: gdate: command not found
./callConspecChecker.sh: line 3: /1000000: syntax error: operand expected (error token is "/1000000")
```

Besides, there appears to be some hardcoded configuration bits in the main shell script.
```
index=$(wc -l < /Users/subhajitsidhanta/Downloads/Spin/training_data.arff)
```

**Comment by ssidhanta** [comment]
Thanks for pointing it out.   
Please re-run the shell script with path of the trace file as an additional file.
/callConspecChecker.sh RYW /Users/subhajitsidhanta/Dropbox/CodeBase\ Log\ ingestion/training_data.arff 
Try running ln -s $(which date) /bin/gdate
Check with ls $(which date) /bin/gdate.
Also check the permission of the Spin folder.
